# Generated by Django 3.0.6 on 2020-05-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200509_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
