# Generated by Django 3.0.6 on 2020-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
