# Generated by Django 3.0.6 on 2020-05-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200509_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
