# Generated by Django 3.0.6 on 2020-05-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conatct',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
