# Generated by Django 3.0.6 on 2020-05-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_conatct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
